### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by louanfontenele** [FdezRomero/whimsical-exporter#1]
![image](https://github.com/FdezRomero/whimsical-exporter/assets/2886066/de9cab88-f370-4a58-8a8a-7cdc1a28710f)

**Comment by aphamHashi** [comment]
Hi @FdezRomero, I just tried your tool again and hit a similar error:

```
? Whimsical folder URL to start export from: https://whimsical.com/folder1-xyaksdfskjkxxxxxx
? Select which formats to export as: SVG
🚀 Launching browser
📄 Opening new page
🔐 Logging in
/workspace/whimsical/whimsical-exporter/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
              ^

Error: No element found for selector: input[type="submit"]
    at assert (/workspace/whimsical/whimsical-exporter/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at IsolatedWorld.click (/workspace/whimsical/whimsical-exporter/node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:215:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async logIn (/workspace/whimsical/whimsical-exporter/dist/index.js:94:5)
    at async init (/workspace/whimsical/whimsical-exporter/dist/index.js:31:5)

Node.js v18.20.5
```

**Comment by aphamHashi** [comment]
@pippobimbo

Seems to get further with your PR: https://github.com/FdezRomero/whimsical-exporter/pull/2

```whimsical-exporter
👋 Welcome to whimsical-exporter
ℹ  All exported files will be saved in /workspace/whimsical/whimsical-exporter/downloads

? Your Whimsical email (username@domain.tld): xxx@gmail.com
? Your Whimsical password: [hidden]
? Whimsical folder URL to start export from: https://whimsical.com/everyone-at-abc-pet-control
? Select which formats to export as: SVG
🚀 Launching browser
📄 Opening new page
🔐 Logging in
📂 Navigating to folder: everyone-at-abc-pet-control
/workspace/whimsical/whimsical-exporter/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js:162
            throw new Error(`Error: failed to find element matching selector "${selector}"`);
                  ^

Error: Error: failed to find element matching selector "[data-wc="folder-content"] > div"
    at ElementHandle.$eval (/workspace/whimsical/whimsical-exporter/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js:162:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadAllItems (/workspace/whimsical/whimsical-exporter/dist/index.js:117:9)
    at async navigateToFolder (/workspace/whimsical/whimsical-exporter/dist/index.js:107:5)
    at async init (/workspace/whimsical/whimsical-exporter/dist/index.js:32:5)

Node.js v18.20.5```

**Comment by FdezRomero** [comment]
I've just merged the fix from #2, but it can be that some other selectors have changed. I don't use Whimsical in my day to day, so it would be great if any of you can check the current selectors and update them in a PR.
